/* prettier-ignore-start */

/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.15.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { GenericId, GenericIdConstructor } from "convex/values";
import type { DataModelFromSchemaDefinition } from "convex/server";
import type { GenericDatabaseReader, GenericDatabaseWriter } from "convex/server";
import type { DocumentByName, TableNamesInDataModel } from "convex/server";
import type { Value } from "convex/values";
import schema from "../schema";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = TableNamesInDataModel<DataModel>;

/**
 * The type of a document stored in Convex.
 */
export type Doc<TableName extends TableNames> = DocumentByName<
  DataModel,
  TableName
>;

/**
 * The type of an `_id` field of a document stored in Convex.
 */
export type Id<TableName extends TableNames> = GenericId<TableName>;

/**
 * A type describing your Convex data model.
 *
 * This type includes information about the tables, documents, and fields in your database.
 * It is used to provide better type safety and autocompletion.
 *
 * @public
 */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

/* prettier-ignore-end */

