/* prettier-ignore-start */

/* eslint-disable */
/**
 * Generated server-side utilities.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.15.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

/**
 * A set of functions for scheduling Convex functions.
 *
 * You can schedule Convex functions to run at a point in the future or
 * periodically using the {@link cron} syntax.
 *
 * @public
 */
export declare const cron: {
  hourly: string;
  daily: string;
  weekly: string;
  monthly: string;
};

/**
 * Define a query in this Convex app's API.
 *
 * @param func - The query function. It receives a {@link QueryCtx} as its first argument.
 * @returns The wrapped query. Include this as an `export` to name it and make it accessible.
 *
 * @public
 */
export declare const query: QueryBuilder<DataModel, "public">;

/**
 * Define a mutation in this Convex app's API.
 *
 * @param func - The mutation function. It receives a {@link MutationCtx} as its first argument.
 * @returns The wrapped mutation. Include this as an `export` to name it and make it accessible.
 *
 * @public
 */
export declare const mutation: MutationBuilder<DataModel, "public">;

/**
 * Define an action in this Convex app's API.
 *
 * Actions are the Convex way of calling third-party APIs, running side effects, or
 * calling multiple Convex functions in a transaction.
 *
 * @param func - The action function. It receives an {@link ActionCtx} as its first argument.
 * @returns The wrapped action. Include this as an `export` to name it and make it accessible.
 *
 * @public
 */
export declare const action: ActionBuilder<DataModel, "public">;

/**
 * Define an HTTP action.
 *
 * HTTP actions are perfect for handling webhooks, responding to HTTP requests, or
 * building REST APIs.
 *
 * @param func - The HTTP action function. It receives an {@link HttpActionCtx} as its first argument.
 * @returns The wrapped HTTP action. Include this as an `export` to name it and make it accessible.
 *
 * @public
 */
export declare const httpAction: HttpActionBuilder;

/**
 * Reference a Convex function.
 *
 * @param functionReference - The function reference, like `api.myModule.myFunction`
 * @returns The function reference
 *
 * @public
 */
export declare function internal<Args extends any[], Output>(
  functionReference: FunctionReference<"internal", Args, Output>
): FunctionReference<"internal", Args, Output>;

/**
 * Reference a Convex function.
 *
 * @param functionReference - The function reference, like `api.myModule.myFunction`
 * @returns The function reference
 *
 * @public
 */
export declare function internalAction<Args extends any[], Output>(
  functionReference: FunctionReference<"internal", Args, Output>
): FunctionReference<"internal", Args, Output>;

/* prettier-ignore-end */

